
services:
  # API Gateway service
  api-gateway:
    build:
      context: ./backend/api-gateway
    ports:
      - "7500:7500"
    depends_on:
      - auth-service
      - restaurant-service
      - order-service
      - review-service
      - user-service
      - employee-service
      - mqtt-broker
    environment:
      - PORT=7500
      - AUTH_SERVICE_URL=http://auth-service:3001
      - RESTAURANT_SERVICE_URL=http://restaurant-service:3002
      - ORDER_SERVICE_URL=http://order-service:3003
      - REVIEW_SERVICE_URL=http://review-service:3004
      - USER_SERVICE_URL=http://user-service:3005
      - EMPLOYEE_SERVICE_URL=http://employee-service:3006
      - JWT_SECRET=${JWT_SECRET}
      - MQTT_BROKER_URL=mqtt://mqtt-broker:1883
    networks:
      - backend-network
    restart: always
    # Add healthcheck
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7500/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Auth Service
  auth-service:
    # ... keep existing code (auth-service configuration)

  # Restaurant Service
  restaurant-service:
    build:
      context: ./backend/restaurant-service
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - JWT_SECRET=${JWT_SECRET}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - MQTT_BROKER_URL=mqtt://mqtt-broker:1883
    networks:
      - backend-network
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3002/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Order Service
  order-service:
    build:
      context: ./backend/order-service
    ports:
      - "3003:3003"
    environment:
      - PORT=3003
      - JWT_SECRET=${JWT_SECRET}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - MQTT_BROKER_URL=mqtt://mqtt-broker:1883
    networks:
      - backend-network
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3003/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Review Service
  review-service:
    # ... keep existing code (review-service configuration)

  # User Service
  user-service:
    build:
      context: ./backend/user-service
    ports:
      - "3005:3005"
    environment:
      - PORT=3005
      - JWT_SECRET=${JWT_SECRET}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - MQTT_BROKER_URL=mqtt://mqtt-broker:1883
    networks:
      - backend-network
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3005/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Employee Service
  employee-service:
    # ... keep existing code (employee-service configuration)

  # MQTT Broker Service
  mqtt-broker:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"  # MQTT port
      - "9001:9001"  # WebSockets port
    volumes:
      - ./backend/mqtt/config:/mosquitto/config
      - ./backend/mqtt/data:/mosquitto/data
      - ./backend/mqtt/log:/mosquitto/log
    networks:
      - backend-network
    restart: always
    healthcheck:
      test: ["CMD", "mosquitto_sub", "-t", "$SYS/broker/uptime", "-C", "1", "-i", "healthcheck", "-W", "3"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  backend-network:
    driver: bridge
