
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://ukrukdqjvvsvfvmqzxdv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVrcnVrZHFqdnZzdmZ2bXF6eGR2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0MDYxMTcsImV4cCI6MjA1ODk4MjExN30.V9T0HKUznzB1Gp1_RpwrDADDWfvRXdtehx5y0u6hK4c";

console.log("Initializing Supabase with URL:", SUPABASE_URL);

// Create the Supabase client with proper configuration
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Check connection and log result
supabase.auth.getSession().then(({ data, error }) => {
  if (error) {
    console.error("Supabase connection error:", error);
  } else {
    console.log("Supabase connection successful, session:", data.session ? "Active" : "None");
  }
});
